name: ddns

on:
  push:
    paths:
      - 'ddns/README.md'
  schedule:
    - cron: '5 * * * *'

env:
  hostname: zhonghe.ddnsfree.com
  check_url: zhonghe.ddnsfree.com:11016/7f77d4ab8bca
  check_code: af6c7363c612

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.check_ddns.outputs.check }}
    steps:
      - name: check ddns
        id: check_ddns
        run: |
          if [[ $(timeout 3 curl -s ${{ env.check_url }}) == ${{ env.check_code }} ]]; then
            echo "check=sucess" >> "$GITHUB_OUTPUT"
          else
            echo "check=failed" >> "$GITHUB_OUTPUT"
          fi

  update:
    needs: check
    if: ${{needs.check.outputs.output == 'failed'}}
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH for Gitee
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts

      - name: Update ddns
        run: |
          cd $(mktemp -d) && git clone ${{ secrets.GITEE_REPO_URL }} --depth=1
          cd ddns && ipv4=$(<ipv4.txt) && echo "${ipv4}"

          alias curl_dynu='curl -s -H "accept: application/json" -H "API-Key: ${{ secrets.DYNU_KEY }}"'

          dns_id=$(curl_dynu -X GET "https://api.dynu.com/v2/dns/getroot/${{ env.hostname }}" | jq .id)
          curl_dynu -X POST "https://api.dynu.com/v2/dns/${dns_id}"  -d "{\"name\": \"${{ env.hostname }}\", \"ipv4Address\": \"${ipv4}\"}"
