name: ddns

on:
  push:
    paths:
      - 'ddns/README.md'
  schedule:
    - cron: '5 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.check_ddns.outputs.check }}
    steps:
      - name: check ddns
        id: check_ddns
        run: |
          if [[ $(timeout 3 curl -s xingdao.ddnsfree.com:11016/7f77d4ab8bca) != af6c7363c612 ]]; then
            echo "check=sucess" >> "$GITHUB_OUTPUT"
          else
            echo "check=failed" >> "$GITHUB_OUTPUT"
          fi

  update:
    needs: check
    if: ${{needs.check.outputs.output}} == "failed"
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH for Gitee
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts

      - name: Update ddns
        run: |
          cd $(mktemp -d) && git clone ${{ secrets.GITEE_REPO_URL }} --depth=1
          cd ddns && ipv4=$(<ip.txt) && echo "${ipv4}"
          body='{"name":"xingdao.ddnsfree.com","ipv4Address":"'${ipv4}'"}'
          curl -s -X POST "https://api.dynu.com/v2/dns/9237025" -H "accept: application/json" -H "API-Key: ${{ secrets.DYNU_KEY }}" -H "Content-Type: application/json" -d "${body}"
